name: Build
on: pull_request
permissions:
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Install and Build 🔧
        run: |
          pnpm install
          pnpm run build
